const initial={
  pipeline:[], projects:[], people:[], solutions:[
    {name:'Privacy-i EDR',company:'소만사',category:'Endpoint · 랜섬웨어',icon:'⌁',desc:'단말 행위 정보를 실시간 수집·분석하고 악성 파일과 행위의 연관 관계를 타임라인으로 제공합니다.',points:['매체제어·출력물보안·백신 통합 Agent','위협 인텔리전스 연동','탐지 단말 네트워크 자동 격리']},
    {name:'Privacy-i DLP',company:'소만사',category:'Endpoint DLP',icon:'▤',desc:'PC에서 유출되는 개인정보와 중요 데이터를 검출·암호화하고 매체, 업로드, 출력물을 통제합니다.',points:['국내 Endpoint DLP 선도 제품','공공·기업·금융 1,000여 고객사','개인정보 검출·암호화']},
    {name:'WebkeeperSG AI DLP',company:'소만사',category:'Network · 생성형 AI',icon:'✦',desc:'네트워크 구간에서 생성형 AI 서비스 사용과 민감 데이터 입력을 통제합니다.',points:['생성형 AI 70여 종 통제','LLM 기반 AI DLP 확장','공공·기업·금융 700여 고객사']}]
};
const KEY='bobjul-sales-public-v1';let data=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(initial);let peopleFilter='all';const $=s=>document.querySelector(s);const fmt=n=>'₩'+Number(n).toLocaleString('ko-KR')+'천';
function persist(){localStorage.setItem(KEY,JSON.stringify(data))}function badge(s){const c=s==='진행'||s==='투입'||s==='수주'?'green':s==='예정'||s==='제안'||s==='후보'?'amber':'';return `<span class="badge ${c}">${s}</span>`}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function projectProduct(p){return p.product||p.requestProduct||p.partner||'-'}
function renderDashboard(){$('#dashboard-projects').innerHTML=data.projects.slice(0,5).map(p=>`<tr><td><b>${escapeHtml(p.name)}</b></td><td>${badge(escapeHtml(p.status||'미지정'))}</td><td>${escapeHtml(projectProduct(p))}</td><td style="white-space:pre-wrap">${escapeHtml(p.inquiry||'-')}</td></tr>`).join('')}
function renderPipeline(){const stages=['발굴','제안','협상','수주'];$('#kanban').innerHTML=stages.map(s=>`<div class="kanban-col"><div class="kanban-title"><span>${s}</span><b>${data.pipeline.filter(x=>x.stage===s).length}</b></div>${data.pipeline.filter(x=>x.stage===s).map(d=>`<article class="deal"><h4>${d.name}</h4><p>${d.client} · ${d.type}<br>담당 ${d.owner}</p><div class="deal-meta"><span>${fmt(d.amount)}</span><span>${s}</span></div></article>`).join('')||'<p style="color:var(--muted);font-size:12px">등록된 기회가 없습니다.</p>'}</div>`).join('')}
function renderProjects(){const q=$('#global-search').value.trim().toLowerCase();$('#project-cards').innerHTML=data.projects.filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q)).map(p=>`<article class="project-card"><h3>${escapeHtml(p.name)}</h3>${badge(escapeHtml(p.status||'미지정'))}<p>확인 요청 제품: ${escapeHtml(projectProduct(p))}</p><p style="white-space:pre-wrap;overflow-wrap:anywhere">문의사항: ${escapeHtml(p.inquiry||'-')}</p></article>`).join('')}
function renderPeople(){const q=$('#global-search').value.trim().toLowerCase(),rows=data.people.filter(p=>(peopleFilter==='all'||p.grade===peopleFilter)&&(!q||JSON.stringify(p).toLowerCase().includes(q)));$('#people-summary').textContent=`${rows.length}명 표시 · 총 ${data.people.length}명`;$('#people-table').innerHTML=rows.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.grade}</td><td>${p.org}</td><td>${p.project}</td><td>${p.period}</td><td>${Number(p.rate).toLocaleString()}</td><td>${badge(p.status)}</td></tr>`).join('')}
function renderSolutions(){$('#solution-cards').innerHTML=data.solutions.map(s=>`<article class="solution-card"><div class="solution-icon">${s.icon}</div><h3>${s.name}</h3><span class="category">${s.company} · ${s.category}</span><p>${s.desc}</p><ul>${s.points.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('')}
function render(){renderDirectory();renderDashboard();renderPipeline();renderProjects();renderPeople();renderSolutions()}
const titles={directory:'등록 정보',dashboard:'22기 영업',pipeline:'영업 파이프라인',projects:'프로젝트 관리',people:'투입 인력 관리',solutions:'보안 솔루션'};function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#page-title').textContent=titles[v];window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{peopleFilter=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));renderPeople()});$('#global-search').oninput=()=>{renderProjects();renderPeople();renderDirectory()};
const schemas={directory:{title:'등록',fields:[['company','회사명','text'],['name','이름','text'],['product','취급제품','text'],['vendor','벤더사명','text'],['overview','제품 개요','textarea'],['references','레퍼런스','textarea']]},pipeline:{title:'신규 영업 기회',fields:[['name','기회명','text'],['client','고객사','text'],['stage','영업 단계','select',['발굴','제안','협상','수주']],['type','유형','select',['인력','솔루션']],['amount','예상 금액(천원)','number'],['owner','담당자','text']]},project:{title:'프로젝트 등록',fields:[['name','사업명','text'],['status','현재 상태(ISP/RFI/RFP 등)','text'],['product','확인 요청 제품','text'],['inquiry','문의사항','textarea']]},person:{title:'인력 등록',fields:[['name','성명','text'],['grade','등급','select',['고급','중급','초급']],['org','소속 / 역할','text'],['project','배치 프로젝트','text'],['period','투입 기간','text'],['rate','단가(천원)','number'],['status','상태','select',['후보','투입','종료']]]}};
function openForm(type){const s=schemas[type];$('#record-type').value=type;$('#dialog-title').textContent=s.title;$('#form-fields').innerHTML=s.fields.map(([n,l,t,opts])=>`<div class="field ${n==='name'||t==='textarea'?'full':''}"><label for="f-${n}">${l}</label>${t==='textarea'?`<textarea id="f-${n}" name="${n}" rows="4" required></textarea>`:t==='select'?`<select id="f-${n}" name="${n}" required>${opts.map(o=>`<option>${o}</option>`).join('')}</select>`:`<input id="f-${n}" name="${n}" type="${t}" ${type==='project'&&n==='status'?'placeholder="예: ISP, RFI, RFP, 제안, 협상"':''} required>`}</div>`).join('');$('#record-dialog').showModal()}
$('#add-btn').onclick=()=>openForm('directory');$('#nav-register').onclick=()=>openForm('directory');$('#directory-add').onclick=()=>openForm('directory');$('#search-btn').onclick=searchDirectory;$('#global-search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchDirectory()}});document.querySelectorAll('.add-pipeline').forEach(b=>b.onclick=()=>openForm('pipeline'));document.querySelectorAll('.add-project').forEach(b=>b.onclick=()=>openForm('project'));document.querySelectorAll('.add-person').forEach(b=>b.onclick=()=>openForm('person'));$('#record-form').addEventListener('submit',e=>{e.preventDefault();if(e.submitter?.value==='cancel'){$('#record-dialog').close();return}const type=$('#record-type').value,obj=Object.fromEntries(new FormData(e.target));['amount','people','mm','cost','rate'].forEach(k=>{if(k in obj)obj[k]=Number(obj[k])});obj.id=Date.now();(data[type==='directory'?'directory':type==='person'?'people':type==='project'?'projects':'pipeline']??=[]).push(obj);persist();render();$('#record-dialog').close();if(type==='directory'){$('#global-search').value='';renderDirectory();go('directory')}showToast('저장되었습니다')});function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'create_sales_opportunity',title:'영업 기회 등록',description:'새 영업 기회를 파이프라인에 등록합니다.',inputSchema:{type:'object',properties:{name:{type:'string'},client:{type:'string'},stage:{enum:['발굴','제안','협상','수주']},type:{enum:['인력','솔루션']},amount:{type:'number'},owner:{type:'string'}},required:['name','client','stage','type','amount','owner'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const item={...input,id:Date.now()};data.pipeline.push(item);persist();render();return {id:item.id,status:'created'}}}).catch(()=>{})}
function renderDirectory(){
  const q=$('#global-search').value.trim().toLocaleLowerCase();
  const rows=(data.directory||[]).filter(r=>['company','name','product','vendor','overview','references'].some(k=>String(r[k]||'').toLocaleLowerCase().includes(q)));
  $('#directory-count').textContent=q?'검색 결과 '+rows.length+'건':'등록 정보 '+rows.length+'건';
  const columns=[['company','회사명'],['name','이름'],['product','취급제품'],['vendor','벤더사명'],['overview','제품 개요'],['references','레퍼런스']];
  $('#directory-results').innerHTML='<table class="directory-table" aria-label="회사 및 제품 등록 정보"><colgroup><col style="width:14%"><col style="width:10%"><col style="width:16%"><col style="width:14%"><col style="width:26%"><col style="width:20%"></colgroup><thead><tr>'+columns.map(([,label])=>'<th scope="col">'+label+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.map(r=>'<tr>'+columns.map(([key])=>'<td>'+escapeHtml(r[key]||'-')+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="6">'+(q?'검색 결과가 없습니다. 다른 검색어를 입력해 주세요.':'아직 등록된 정보가 없습니다. 등록 버튼을 눌러 회사와 제품 정보를 추가하세요.')+'</td></tr>')+'</tbody></table>';
}
function searchDirectory(){renderDirectory();go('directory')}

render();
