const initial={
  pipeline:[], projects:[], people:[], solutions:[
    {name:'Privacy-i EDR',company:'소만사',category:'Endpoint · 랜섬웨어',icon:'⌁',desc:'단말 행위 정보를 실시간 수집·분석하고 악성 파일과 행위의 연관 관계를 타임라인으로 제공합니다.',points:['매체제어·출력물보안·백신 통합 Agent','위협 인텔리전스 연동','탐지 단말 네트워크 자동 격리']},
    {name:'Privacy-i DLP',company:'소만사',category:'Endpoint DLP',icon:'▤',desc:'PC에서 유출되는 개인정보와 중요 데이터를 검출·암호화하고 매체, 업로드, 출력물을 통제합니다.',points:['국내 Endpoint DLP 선도 제품','공공·기업·금융 1,000여 고객사','개인정보 검출·암호화']},
    {name:'WebkeeperSG AI DLP',company:'소만사',category:'Network · 생성형 AI',icon:'✦',desc:'네트워크 구간에서 생성형 AI 서비스 사용과 민감 데이터 입력을 통제합니다.',points:['생성형 AI 70여 종 통제','LLM 기반 AI DLP 확장','공공·기업·금융 700여 고객사']}]
};
const KEY='bobjul-sales-public-v1';let data=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(initial);let peopleFilter='all';const $=s=>document.querySelector(s);const fmt=n=>'₩'+Number(n).toLocaleString('ko-KR')+'천';
function persist(){localStorage.setItem(KEY,JSON.stringify(data))}function badge(s){const c=s==='진행'||s==='투입'||s==='수주'?'green':s==='예정'||s==='제안'||s==='후보'?'amber':'';return `<span class="badge ${c}">${s}</span>`}
function projectProduct(p){return p.product||p.requestProduct||p.partner||'-'}
function renderDashboard(){const rev=data.projects.reduce((a,p)=>a+Number(p.cost||0),0),products=new Set(data.projects.map(projectProduct).filter(x=>x&&x!=='-')).size;$('#total-revenue').textContent=fmt(rev);$('#total-products').textContent=products.toLocaleString('ko-KR');$('#total-people').textContent=data.people.length+'명';$('#candidate-count').textContent='후보 '+data.people.filter(p=>p.status==='후보').length+'명 포함';$('#active-projects').textContent=data.projects.filter(p=>p.status!=='완료').length;const stages=['발굴','제안','협상','수주'];$('#stage-bars').innerHTML=stages.map(s=>{const n=data.pipeline.filter(x=>x.stage===s).length,p=Math.max(8,n/Math.max(1,data.pipeline.length)*100);return `<div class="stage-row"><span>${s}</span><div class="bar"><i style="width:${p}%"></i></div><b>${n}</b></div>`}).join('');$('#dashboard-projects').innerHTML=data.projects.slice(0,5).map(p=>`<tr><td><b>${p.name}</b></td><td>${p.client}</td><td>${projectProduct(p)}</td><td>${badge(p.status)}</td></tr>`).join('')}
function renderPipeline(){const stages=['발굴','제안','협상','수주'];$('#kanban').innerHTML=stages.map(s=>`<div class="kanban-col"><div class="kanban-title"><span>${s}</span><b>${data.pipeline.filter(x=>x.stage===s).length}</b></div>${data.pipeline.filter(x=>x.stage===s).map(d=>`<article class="deal"><h4>${d.name}</h4><p>${d.client} · ${d.type}<br>담당 ${d.owner}</p><div class="deal-meta"><span>${fmt(d.amount)}</span><span>${s}</span></div></article>`).join('')||'<p style="color:var(--muted);font-size:12px">등록된 기회가 없습니다.</p>'}</div>`).join('')}
function renderProjects(){const q=$('#global-search').value.trim().toLowerCase();$('#project-cards').innerHTML=data.projects.filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q)).map(p=>`<article class="project-card"><p class="eyebrow">${p.client}</p><h3>${p.name}</h3><p>${projectProduct(p)}</p>${badge(p.status||'확인')}</article>`).join('')}
function renderPeople(){const q=$('#global-search').value.trim().toLowerCase(),rows=data.people.filter(p=>(peopleFilter==='all'||p.grade===peopleFilter)&&(!q||JSON.stringify(p).toLowerCase().includes(q)));$('#people-summary').textContent=`${rows.length}명 표시 · 총 ${data.people.length}명`;$('#people-table').innerHTML=rows.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.grade}</td><td>${p.org}</td><td>${p.project}</td><td>${p.period}</td><td>${Number(p.rate).toLocaleString()}</td><td>${badge(p.status)}</td></tr>`).join('')}
function renderSolutions(){$('#solution-cards').innerHTML=data.solutions.map(s=>`<article class="solution-card"><div class="solution-icon">${s.icon}</div><h3>${s.name}</h3><span class="category">${s.company} · ${s.category}</span><p>${s.desc}</p><ul>${s.points.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('')}
function render(){renderDashboard();renderPipeline();renderProjects();renderPeople();renderSolutions()}
const titles={dashboard:'영업 현황',pipeline:'영업 파이프라인',projects:'프로젝트 관리',people:'투입 인력 관리',solutions:'보안 솔루션'};function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#page-title').textContent=titles[v];window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{peopleFilter=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));renderPeople()});$('#global-search').oninput=()=>{renderProjects();renderPeople()};
const schemas={pipeline:{title:'신규 영업 기회',fields:[['name','기회명','text'],['client','고객사','text'],['stage','영업 단계','select',['발굴','제안','협상','수주']],['type','유형','select',['인력','솔루션']],['amount','예상 금액(천원)','number'],['owner','담당자','text']]},project:{title:'프로젝트 등록',fields:[['name','프로젝트명','text'],['client','고객사','text'],['product','확인 요청 제품','text']]},person:{title:'인력 등록',fields:[['name','성명','text'],['grade','등급','select',['고급','중급','초급']],['org','소속 / 역할','text'],['project','배치 프로젝트','text'],['period','투입 기간','text'],['rate','단가(천원)','number'],['status','상태','select',['후보','투입','종료']]]}};
function openForm(type){const s=schemas[type];$('#record-type').value=type;$('#dialog-title').textContent=s.title;$('#form-fields').innerHTML=s.fields.map(([n,l,t,opts])=>`<div class="field ${n==='name'?'full':''}"><label for="f-${n}">${l}</label>${t==='select'?`<select id="f-${n}" name="${n}" required>${opts.map(o=>`<option>${o}</option>`).join('')}</select>`:`<input id="f-${n}" name="${n}" type="${t}" required>`}</div>`).join('');$('#record-dialog').showModal()}
$('#add-btn').onclick=()=>openForm('pipeline');document.querySelectorAll('.add-pipeline').forEach(b=>b.onclick=()=>openForm('pipeline'));document.querySelectorAll('.add-project').forEach(b=>b.onclick=()=>openForm('project'));document.querySelectorAll('.add-person').forEach(b=>b.onclick=()=>openForm('person'));$('#record-form').addEventListener('submit',e=>{e.preventDefault();const type=$('#record-type').value,obj=Object.fromEntries(new FormData(e.target));['amount','people','mm','cost','rate'].forEach(k=>{if(k in obj)obj[k]=Number(obj[k])});obj.id=Date.now();data[type==='person'?'people':type==='project'?'projects':'pipeline'].push(obj);persist();render();$('#record-dialog').close();showToast('저장되었습니다')});function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'create_sales_opportunity',title:'영업 기회 등록',description:'새 영업 기회를 파이프라인에 등록합니다.',inputSchema:{type:'object',properties:{name:{type:'string'},client:{type:'string'},stage:{enum:['발굴','제안','협상','수주']},type:{enum:['인력','솔루션']},amount:{type:'number'},owner:{type:'string'}},required:['name','client','stage','type','amount','owner'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const item={...input,id:Date.now()};data.pipeline.push(item);persist();render();return {id:item.id,status:'created'}}}).catch(()=>{})}
render();
